dy:
  core:
    env: staging
    custom:
      custom1: this is custom1
      custom2: this is custom2
    cors:
      enabled: true
    swagger:
      enabled: true
      versions:
        - version: 1.0
          group-name: api-1.0
          apis: "samples.demo.web"
          regex: ""  # "/api/v1/.*|/api/daemon/v1/.*"
          title: "Application API 1.0"
          description: "API 1.0 documentation"
          terms-of-service-url: ""
          license: ""
          licenseUrl: ""
          contact-name: ""
          contact-url: ""
          contact-email: ""
#        - version: 1.1
#          group-name: h5-1.0
#          apis: ""
#          regex: ""
#          title: "Application h5 1.0"
#          description: "h5 1.0 documentation"
#          terms-of-service-url: ""
#          license: ""
#          licenseUrl: ""
#          contact-name: ""
#          contact-url: ""
#          contact-email: ""

  security:
    enabled: true
    jwt:
      expiration: 2500000
      header: Authorization
      secret: 1100.game.dev
      token-head: Bearer
    cors-permit:
      patterns: /**
    resource-permit:
      patterns: /, /*.html, /favicon.ico, /**/*.html, /**/*.css, /**/*.js, /webjars/**, /swagger-resources/**, /*/api-docs
    auth-permit:
      patterns: /api/hello