spring:
  datasource:
    url: jdbc:mysql://172.81.252.75:13030/dairy_dev?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: dairy
    password: dairy_dev789456!@#
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: samples.mybatis.model